
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: nomster_app_new_development

test:
  <<: *default
  database: nomster_app_new_test

production:
  <<: *default
  database: nomster_app_new_production
  #username: nomster_app_new
  #password: <%= ENV['NOMSTER_APP_NEW_DATABASE_PASSWORD'] %>
